name: waveform_visualizer
description: A beautiful animated waveform widget for Flutter with real-time visualization capabilities.
version: 1.0.0
# Replace YOUR_USERNAME with your actual GitHub username before publishing
homepage: https://github.com/jbergloda1/flutter_waveform_visualizer
repository: https://github.com/jbergloda1/flutter_waveform_visualizer
issue_tracker: https://github.com/jbergloda1/flutter_waveform_visualizer/issues
documentation: https://github.com/jbergloda1/flutter_waveform_visualizer

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# The following section is package-specific configuration.
topics:
  - flutter
  - waveform
  - animation
  - audio-visualization 